user:
  handler: src/handler/user/index.handler
  events:
    - http:
        method: post
        path: api/user/
        cors: true
        authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: adminApiGatewayAuthorizer
