Resources:
  SeqManage:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: SeqManage
      AttributeDefinitions:
        -
          AttributeName: tableName
          AttributeType: S
        -
          AttributeName: groupId
          AttributeType: S
      KeySchema:
        -
          AttributeName: tableName
          KeyType: HASH
        -
          AttributeName: groupId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
